# Generated by Django 5.2 on 2026-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_type',
            field=models.CharField(choices=[('fa', 'Font Awesome'), ('svg', 'SVG URL')], default='fa', max_length=10),
        ),
    ]
